//! v315 (S57, DP 2026-10-07 21:53 "Go on 1 & 2" — joinstr-fit-r5, the wallet side, step 2): THE WALLET'S MUSIG2 SIGNER
//! (BIP-327) for the Mix. A pool's shared output is one taproot key made from every member's key; the wallet's key signs
//! its share of every pool signature here, on the phone — it is never handed to anyone (r5: "the wallet makes every
//! signature"). Built on the `musig2` crate at the version joinstr v2 signs with (0.4.1), so the wallet's signatures
//! match the pool's.
//!
//! The one rule that keeps the key safe: A NONCE IS USED ONCE. A secret nonce lives only in this process's memory, in a
//! NonceStore keyed by the round's session id; signing takes it OUT of the store (it cannot be used twice), a session id
//! is never reused, and nothing here is ever written to storage, the cloud copy, a backup file or the Black start kit —
//! a restored phone starts with no nonces and simply makes new ones. Every nonce is generated by BIP-327's NonceGen from
//! fresh randomness AND the secret key, the pool key, the message and the session id, so a weak random source alone
//! cannot repeat one.

use std::collections::{HashMap, HashSet};

use musig2::secp::{MaybeScalar, Point, Scalar};
use musig2::{AggNonce, KeyAggContext, LiftedSignature, PartialSignature, PubNonce, SecNonce};
use rand::RngCore;

use crate::error::{LijError, LijResult};

fn err(what: &str, e: impl std::fmt::Display) -> LijError {
    LijError::Key(format!("musig: {what}: {e}"))
}

/// A pool's aggregate key: the members' keys (BIP-327 KeyAgg), optionally sorted first (BIP-327 KeySort — joinstr v2
/// sorts), then plain tweaks in order (joinstr v2's BIP-328 /0/i), then optionally the BIP-86 taproot tweak with no
/// script tree (joinstr v2's `with_unspendable_taproot_tweak`).
pub struct PoolKey {
    ctx: KeyAggContext,
}

impl PoolKey {
    pub fn new(pubkeys: &[[u8; 33]], sort: bool, plain_tweaks: &[[u8; 32]], taproot: bool) -> LijResult<Self> {
        if pubkeys.is_empty() {
            return Err(err("key aggregation", "no keys"));
        }
        let mut points: Vec<Point> = pubkeys
            .iter()
            .map(|k| Point::from_slice(k).map_err(|e| err("a member key", e)))
            .collect::<LijResult<_>>()?;
        if sort {
            points.sort_by_key(|p| p.serialize());
        }
        let mut ctx = KeyAggContext::new(points).map_err(|e| err("key aggregation", e))?;
        for t in plain_tweaks {
            let s = MaybeScalar::from_slice(t).map_err(|e| err("a plain tweak", e))?;
            ctx = ctx.with_plain_tweak(s).map_err(|e| err("a plain tweak", e))?;
        }
        if taproot {
            ctx = ctx.with_unspendable_taproot_tweak().map_err(|e| err("the taproot tweak", e))?;
        }
        Ok(Self { ctx })
    }

    /// The x-only key the pool's output pays (after every tweak) — the taproot output key.
    pub fn output_xonly(&self) -> [u8; 32] {
        self.ctx.aggregated_pubkey::<Point>().serialize_xonly()
    }

    /// The aggregate key before any tweak (BIP-327's KeyAgg result), x-only.
    pub fn untweaked_xonly(&self) -> [u8; 32] {
        self.ctx.aggregated_pubkey_untweaked::<Point>().serialize_xonly()
    }
}

/// The wallet's secret nonces, one per signing session, in memory only.
#[derive(Default)]
pub struct NonceStore {
    live: HashMap<String, SecNonce>,
    seen: HashSet<String>,
}

impl NonceStore {
    pub fn new() -> Self {
        Self::default()
    }

    /// Make the nonce for one signing session; returns the public nonce (66 bytes) to send to the pool. A session id
    /// can be used once in the life of this store — a second call is refused.
    pub fn create(&mut self, session: &str, seckey: &[u8; 32], pool: &PoolKey, message: Option<&[u8]>) -> LijResult<[u8; 66]> {
        if session.is_empty() || !self.seen.insert(session.to_string()) {
            return Err(err("nonce", "this session already had a nonce — a nonce is never made twice"));
        }
        let sk = Scalar::from_slice(seckey).map_err(|e| err("secret key", e))?;
        let mut seed = [0u8; 32];
        rand::thread_rng().fill_bytes(&mut seed);
        let agg: Point = pool.ctx.aggregated_pubkey();
        let mut b = SecNonce::build_with_seckey(seed, sk).with_aggregated_pubkey(agg).with_extra_input(&session);
        if let Some(m) = message.as_ref() {
            b = b.with_message(m);
        }
        let sec = b.build();
        let public = sec.public_nonce().serialize();
        self.live.insert(session.to_string(), sec);
        Ok(public)
    }

    /// Sign the session's message with the session's nonce — the nonce leaves the store here and can never sign again.
    pub fn sign(&mut self, session: &str, seckey: &[u8; 32], pool: &PoolKey, aggnonce: &[u8; 66], message: &[u8]) -> LijResult<[u8; 32]> {
        let sec = self
            .live
            .remove(session)
            .ok_or_else(|| err("sign", "no nonce for this session (already used, or never made here)"))?;
        let sk = Scalar::from_slice(seckey).map_err(|e| err("secret key", e))?;
        let agg = AggNonce::from_bytes(aggnonce).map_err(|e| err("aggregated nonce", e))?;
        let partial: PartialSignature = musig2::sign_partial(&pool.ctx, sk, sec, &agg, message).map_err(|e| err("sign", e))?;
        Ok(partial.serialize())
    }

    /// How many nonces wait for a signature (for a status line; never their values).
    pub fn pending(&self) -> usize {
        self.live.len()
    }
}

/// Sum the members' public nonces into the round's aggregated nonce (66 bytes).
pub fn aggregate_nonces(pubnonces: &[[u8; 66]]) -> LijResult<[u8; 66]> {
    let ns: Vec<PubNonce> = pubnonces
        .iter()
        .map(|n| PubNonce::from_bytes(n).map_err(|e| err("a public nonce", e)))
        .collect::<LijResult<_>>()?;
    Ok(AggNonce::sum(ns).serialize())
}

/// Check one member's partial signature before it is aggregated (a bad one names its signer).
pub fn verify_partial(
    pool: &PoolKey, partial: &[u8; 32], aggnonce: &[u8; 66], member_pubkey: &[u8; 33], member_pubnonce: &[u8; 66], message: &[u8],
) -> LijResult<()> {
    let s = MaybeScalar::from_slice(partial).map_err(|e| err("a partial signature", e))?;
    let agg = AggNonce::from_bytes(aggnonce).map_err(|e| err("aggregated nonce", e))?;
    let pk = Point::from_slice(member_pubkey).map_err(|e| err("a member key", e))?;
    let pn = PubNonce::from_bytes(member_pubnonce).map_err(|e| err("a public nonce", e))?;
    musig2::verify_partial(&pool.ctx, s, &agg, pk, &pn, message).map_err(|e| err("a partial signature does not verify", e))
}

/// The pool's final BIP-340 signature (64 bytes) from every member's partial signature.
pub fn aggregate_signatures(pool: &PoolKey, aggnonce: &[u8; 66], partials: &[[u8; 32]], message: &[u8]) -> LijResult<[u8; 64]> {
    let agg = AggNonce::from_bytes(aggnonce).map_err(|e| err("aggregated nonce", e))?;
    let ps: Vec<MaybeScalar> = partials
        .iter()
        .map(|p| MaybeScalar::from_slice(p).map_err(|e| err("a partial signature", e)))
        .collect::<LijResult<_>>()?;
    let sig: LiftedSignature = musig2::aggregate_partial_signatures(&pool.ctx, &agg, ps, message).map_err(|e| err("aggregate", e))?;
    Ok(sig.serialize())
}

#[cfg(test)]
mod tests {
    use super::*;
    use bitcoin::secp256k1::{schnorr, Message, Secp256k1, SecretKey, XOnlyPublicKey};

    fn h(s: &str) -> Vec<u8> { hex::decode(s).unwrap() }
    fn k33(s: &str) -> [u8; 33] { h(s).try_into().unwrap() }

    // BIP-327 key_agg_vectors.json — KeyAgg without sorting
    const X1: &str = "02F9308A019258C31049344F85F89D5229B531C845836F99B08601F113BCE036F9";
    const X2: &str = "03DFF1D77F2A671C5F36183726DB2341BE58FEAE1DA2DECED843240F7B502BA659";
    const X3: &str = "023590A94E768F8E1815C2F24B4D80A8E3149316C3518CE7B7AD338368D038CA66";

    #[test]
    fn v315_bip327_key_aggregation_vectors() {
        let (x1, x2, x3) = (k33(X1), k33(X2), k33(X3));
        let cases: [(Vec<[u8; 33]>, &str); 4] = [
            (vec![x1, x2, x3], "90539EEDE565F5D054F32CC0C220126889ED1E5D193BAF15AEF344FE59D4610C"),
            (vec![x3, x2, x1], "6204DE8B083426DC6EAF9502D27024D53FC826BF7D2012148A0575435DF54B2B"),
            (vec![x1, x1, x1], "B436E3BAD62B8CD409969A224731C193D051162D8C5AE8B109306127DA3AA935"),
            (vec![x1, x1, x2, x2], "69BC22BFA5D106306E48A20679DE1D7389386124D07571D0D872686028C26A3E"),
        ];
        for (keys, want) in cases {
            let pk = PoolKey::new(&keys, false, &[], false).unwrap();
            assert_eq!(hex::encode_upper(pk.untweaked_xonly()), want);
        }
        // sorting makes the order of the members irrelevant (joinstr v2 sorts)
        let a = PoolKey::new(&[x1, x2, x3], true, &[], false).unwrap();
        let b = PoolKey::new(&[x3, x1, x2], true, &[], false).unwrap();
        assert_eq!(a.untweaked_xonly(), b.untweaked_xonly());
    }

    fn members(n: usize) -> Vec<([u8; 32], [u8; 33])> {
        let secp = Secp256k1::new();
        (0..n).map(|i| {
            let mut b = [0u8; 32]; b[31] = (i as u8) + 7; b[0] = 0x42;
            let sk = SecretKey::from_slice(&b).unwrap();
            (sk.secret_bytes(), sk.public_key(&secp).serialize())
        }).collect()
    }

    #[test]
    fn v315_a_pool_signs_and_an_independent_bip340_verifier_accepts() {
        // five members, two plain tweaks then the taproot tweak — the shape of a joinstr v2 pool key
        let m = members(5);
        let keys: Vec<[u8; 33]> = m.iter().map(|x| x.1).collect();
        let t0 = [1u8; 32]; let t1 = [2u8; 32];
        let pool = PoolKey::new(&keys, true, &[t0, t1], true).unwrap();
        let msg = [9u8; 32];
        let mut stores: Vec<NonceStore> = (0..5).map(|_| NonceStore::new()).collect();
        let pubnonces: Vec<[u8; 66]> = (0..5).map(|i| stores[i].create("round-1", &m[i].0, &pool, Some(&msg)).unwrap()).collect();
        let agg = aggregate_nonces(&pubnonces).unwrap();
        let partials: Vec<[u8; 32]> = (0..5).map(|i| stores[i].sign("round-1", &m[i].0, &pool, &agg, &msg).unwrap()).collect();
        for i in 0..5 { verify_partial(&pool, &partials[i], &agg, &m[i].1, &pubnonces[i], &msg).unwrap(); }
        let sig = aggregate_signatures(&pool, &agg, &partials, &msg).unwrap();
        // rust-bitcoin's libsecp256k1 (0.29) — a different code path from the musig2 crate's — checks it
        let secp = Secp256k1::verification_only();
        let xo = XOnlyPublicKey::from_slice(&pool.output_xonly()).unwrap();
        secp.verify_schnorr(&schnorr::Signature::from_slice(&sig).unwrap(), &Message::from_digest(msg), &xo).unwrap();
        assert!(stores.iter().all(|s| s.pending() == 0), "every nonce left its store when it signed");
    }

    #[test]
    fn v315_a_nonce_is_used_once() {
        let m = members(2);
        let keys: Vec<[u8; 33]> = m.iter().map(|x| x.1).collect();
        let pool = PoolKey::new(&keys, true, &[], true).unwrap();
        let msg = [3u8; 32];
        let mut a = NonceStore::new();
        let mut b = NonceStore::new();
        let na = a.create("s", &m[0].0, &pool, None).unwrap();
        assert!(a.create("s", &m[0].0, &pool, None).is_err(), "a second nonce for one session is refused");
        let nb = b.create("s", &m[1].0, &pool, None).unwrap();
        let agg = aggregate_nonces(&[na, nb]).unwrap();
        a.sign("s", &m[0].0, &pool, &agg, &msg).unwrap();
        assert!(a.sign("s", &m[0].0, &pool, &agg, &msg).is_err(), "signing twice with one nonce is impossible");
        assert!(a.create("s", &m[0].0, &pool, None).is_err(), "a used session id never gets a new nonce");
        assert!(NonceStore::new().sign("x", &m[0].0, &pool, &agg, &msg).is_err(), "no nonce, no signature");
    }

    #[test]
    fn v315_a_bad_partial_is_caught_and_named() {
        let m = members(3);
        let keys: Vec<[u8; 33]> = m.iter().map(|x| x.1).collect();
        let pool = PoolKey::new(&keys, true, &[], true).unwrap();
        let msg = [5u8; 32];
        let mut st: Vec<NonceStore> = (0..3).map(|_| NonceStore::new()).collect();
        let pn: Vec<[u8; 66]> = (0..3).map(|i| st[i].create("r", &m[i].0, &pool, Some(&msg)).unwrap()).collect();
        let agg = aggregate_nonces(&pn).unwrap();
        let mut ps: Vec<[u8; 32]> = (0..3).map(|i| st[i].sign("r", &m[i].0, &pool, &agg, &msg).unwrap()).collect();
        ps[1][31] ^= 1;
        assert!(verify_partial(&pool, &ps[1], &agg, &m[1].1, &pn[1], &msg).is_err(), "member 2's altered partial fails");
        assert!(verify_partial(&pool, &ps[0], &agg, &m[0].1, &pn[0], &msg).is_ok());
        assert!(aggregate_signatures(&pool, &agg, &ps, &msg).is_err(), "an altered partial makes no valid signature");
    }
}
